version: '2'

services:
  app:
    image: atnartur/chairs-game:latest
    build:
      context: .
    ports:
      - 5000
    networks:
      - web
    environment:
      VIRTUAL_HOST: chairs.atnartur.ru

networks:
  web:
    external:
      name: web